// -*- C++ -*- generated by wxGlade 0.4.1 on Mon Jun 30 11:13:15 2008

#include <wx/wx.h>
#include <wx/image.h>
// begin wxGlade: ::dependencies
#include <wx/notebook.h>
// end wxGlade


#ifndef MYTEST_H
#define MYTEST_H


enum {
  GridSize = 15
};

class MyFrame: public wxFrame {
public:
    // begin wxGlade: MyFrame::ids
    // end wxGlade

    MyFrame(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:
    // begin wxGlade: MyFrame::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: MyFrame::attributes
    wxPanel* notebook_1_pane_1;
    wxPanel* notebook_1_pane_2;
    wxNotebook* notebook_1;
    // end wxGlade
    void FillVTK(wxPanel *notebook_1_pane_1, wxGridSizer *sizer);

    DECLARE_EVENT_TABLE();

public:
    void OnNotebookChanged(wxNotebookEvent &event); // wxGlade: <event_handler>
    void OnNoteBookChanging(wxNotebookEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // MYTEST_H
